const ActionType = {
    AUTHENTICATE: "AUTHENTICATE",
    OPENCART: "OPENCART",
    COMPANY: "COMPANY",
    PRODUCTS: "PRODUCTS",
    USER: "USER",
    MYACCOUNTOPTION: "MYACCOUNTOPTION",
    USERWISHLIST: "USERWISHLIST",
    USERLOCALWISHLIST: "USERLOCALWISHLIST",
    SINGLEPRODUCT: "SINGLEPRODUCT",
    USERCART: "USERCART",
    USERLOCALCART: "USERLOCALCART",
    TOTAL: "TOTAL",
    DISCOUNT: "DISCOUNT",
    PRODUCTREVIEW: "PRODUCTREVIEW",
    DISCOUNTOFFER: "DISCOUNTOFFER",
    HEADER: "HEADER",
    FOOTER: "FOOTER",
    SHIPPING: "SHIPPING",
    COUPONDISABLE: "COUPONDISABLE",
    SUBTOTAL: "SUBTOTAL",
    COUPON:"COUPON",
    ORDERDETIALS:"ORDERDETIALS",
    ISMOBILEVIEW:"ISMOBILEVIEW"
}

export default ActionType;