const ActionType = {
    AUTHENTICATE: "AUTHENTICATE",
    OPENCART: "OPENCART",
    COMPANY: "COMPANY",
    PRODUCTS: "PRODUCTS",
    USER: "USER",
    MYACCOUNTOPTION: "MYACCOUNTOPTION",
    USERWISHLIST: "USERWISHLIST",
    USERLOCALWISHLIST: "USERLOCALWISHLIST",
    SINGLEPRODUCT: "SINGLEPRODUCT",
    USERCART: "USERCART",
    USERLOCALCART:"USERLOCALCART"
}

export default ActionType;